steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/olaf-backend', './backend']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/olaf-backend']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - run
      - deploy
      - olaf-backend
      - --image=gcr.io/$PROJECT_ID/olaf-backend
      - --region=asia-east1
      - --platform=managed
      - --allow-unauthenticated
      - --port=8080
      - --memory=2Gi
      - --cpu=2
      - --timeout=300
      - --concurrency=80
      - --env-vars-file=backend/env.yaml
      - --update-secrets=GOOGLE_API_KEY=GOOGLE_API_KEY:latest,FIREBASE_ADMIN_PROJECT_ID=FIREBASE_ADMIN_PROJECT_ID:latest,FIREBASE_ADMIN_CLIENT_EMAIL=FIREBASE_ADMIN_CLIENT_EMAIL:latest,FIREBASE_ADMIN_PRIVATE_KEY=FIREBASE_ADMIN_PRIVATE_KEY:latest
images:
  - 'gcr.io/$PROJECT_ID/olaf-backend'

options:
  logging: CLOUD_LOGGING_ONLY
